name: Deploy preview with ftp

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.1'
          extended: true

      - name: Import
        run: bash ./update_content.sh
        
      - name: Build
        run: hugo --minify --gc -b http://www.ids.osaka-u.ac.jp/test/preview/${{ github.sha }}

      - name: Deploy
        run: echo "{{ $secrets.SSH_KEY}} > key && chmod 600 key
        run: rsync -avz --dry-run --delete -e "ssh -i key" ./public/* {{ $secrets.SSH_USER }}@{{ $secrets.SSH_SERVER }}:{{ $secrets.REMOTE_PATH}}/test/preview/${{ github.sha }}/
        run: echo http://www.ids.osaka-u.ac.jp/test/preview/${{ github.sha }}
